### ISSUE TITLE
[skrypt] Ogonki w linkach

### ISSUE THREAD

**Issue by zwiastunsw** [irdpl/wcag#27]
Skrypt generuje w różnych miejscach łącza do plików lub do kotwic w plikach w oparciu o polskie nazwy KS lub brzmienie terminów słownikowych. Niektóre z polskich "ogonków" odwzorowuje na odpowiedniki łacińskie, ale innych nie (np. ł odwzorowuje na -, ś i ć zjada). W efekcie łącza są zerwane.

**Comment by speplinski** [comment]
w gałęzi (branch) `structure-update` poprawiłem sposób generowania linków do wszystkich kryteriów sukcesu oraz linki do słownika (wraz z posłami odmianami).
