### ISSUE TITLE
[skrypt] Etykiety Note i Example zamiast Uwaga i Przykład

### ISSUE THREAD

**Issue by zwiastunsw** [irdpl/wcag#28]
Skrypt oznacza etykietami _Note_ i _Example_ fragmenty tekstu wynikowego WCAG. Nie udało mi się zlokalizować miejsca, w którym trzeba zmodyfikować kod, aby te słowa zastąpić polskimi _Uwaga_ i _Przykład_.

**Comment by speplinski** [comment]
@rotnicki przejrzałem i podmieniłem wszystkie teksty `Note` i `Example` w kodzie ... ale mimo wszystko w KS generują się napisy angielskie. Masz może pomysł, gdzie to jeszcze może być?

**Comment by speplinski** [comment]
Wersja 2.2 zawiera mowyfikację, gdzie te elementy są przeniesione do skryptów XSLT.
