### ISSUE TITLE
[skrypt] Angielskie dodatki i zmiana logo W3C na nasze

### ISSUE THREAD

**Issue by zwiastunsw** [irdpl/wcag#29]
W [wynikowym dokumencie](https://wcag.irdpl.pl/guidelines/22/) niektóre fragmenty są osadzane w języku angielskim. Ponadto całość jest oznaczona za pomocą logo W3C. Na szybko potrzebny jest przede wszystkim sposób, aby zastąpić logo w3c innym znakiem (np. naszym roboczym logo) oraz dodać wyraźny nagłówek, informujący, że to robocza wersja polskiego tłumaczenia.  
Kwestie innych osadzonych fragmentów angielskich nie są tak pilne.

**Comment by rotnicki** [comment]
@zwiastunsw czy to zgłoszenie należy traktować jako prośbę o pomoc w znalezieniu sposobu na tą "podmiankę"

**Comment by speplinski** [comment]
@rotnicki przygotowałem wersję, która te błędy, o których wspomina @zwiastunsw koryguje (branch `structure-update`).
Tylko tam zmieniłem kilkaset (jak nie więcej) odnośników, sposób automatycznego budowania struktury, literówki, etc.
Zostało jeszcze poprawnie automatycznego generowania części linków w understanding (struktura i powiązania już się poprawnie generują).

**Comment by speplinski** [comment]
Ostro nad tym siedzę, aby to jak najszybciej zmergeować i móc pracować na plikach, które się poprawnie generują. W obecnej strukturze przy generowaniu dokumentów są setki błędów i ostrzeżeń. 

Jak masz możliwość @rotnicki to zerknij na branch `structure-update`, aby "na drugą rękę" sprawdzić, czy wszystko jest ok, przed połączeniem tego z główną gałęzią.
