### ISSUE TITLE
Niepotrzebne zastępowanie łączy do technik

### ISSUE THREAD

**Issue by zwiastunsw** [irdpl/wcag#45]
Nazwy technik zostały przetłumaczone na język polski. Z jakiegoś, niepojętego powodu, część łączy jest zastępowana łączami wygenerowanymi przez system, np. w plikach:

- understanding/tresc-nietekstowa  
- understanding/trzy-blyski-lub-wartosci-ponizej-progu
- understanding/nietypowe-slowa

Spróbuj coś z tym począć.

**Comment by speplinski** [comment]
modyfikacja wprowadzona.

**Comment by zwiastunsw** [comment]
Sprawdź jeszcze, bo ni widzę, by coś się zmieniło, np. 
![chrome_H6bDbS1ZKn](https://github.com/irdpl/wcag/assets/29527200/ef626fdb-e050-4c3f-b464-5a60bbeaef91)

To z dok.: understanding/skroty. Wszystkie te łącza są wpisane do plików źódłowych po polsku (zostaje tylko adres do strony w3c)

**Comment by zwiastunsw** [comment]
PS wygląda na to, że naprawione. Prawdopodobnie zamieniał tam, gdzie w adresach było odniesienie /WCAG21/Techniques zamiast /WCAG22/Techniques
