### ISSUE TITLE
Nazwa strony objaśnień z zasadami testowymi dla kryteriów sukcesu WCAG

### ISSUE THREAD

**Issue by speplinski** [irdpl/wcag#46]
Strona "Objaśnienie zasad testowych dla kryteriów sukcesu WCAG" ma angielską nazwę "understanding/understanding-act-rules". Czy nie powinniśmy tego uspójnić? Pozostałe podstrony w ramach "understanding" są po polsku.

**Comment by zwiastunsw** [comment]
Dotyczy to grupy wszystkich plików w katalogu głównym /understanding: 

about.html- powinien mieć tytuł: o-objasnieniach.html
conformance.html- powinien mieć tytuł: zgodnosc.html
documenting-accessibility-support.html- powinien mieć tytuł: dokumentowanie-obslugi-dostepnosci.html
intro.html- powinien mieć tytuł: wstep.html
refer-to-wcag.html - powinien mieć tytuł: odwolania-do-wcag.html
understanding-act-rules.html - powinien mieć tytuł: objasnienie-zasad-testowych.html
understanding-metadata.html - powinien mieć tytuł: objasnienie-metadanych.html
understanding-techniques.html- powinien mieć tytuł: objasnienie-technik.html

Próbowałem tak zrobić i zastosować również polskie nazwy w odwołaniach  wewnątrz plików. 
Ale, gdy zmieniłem nazwy na polskie, to w ogóle tych plików system nie uwzględniał (nie były przenoszone do katalogu wynikowego /understanding na github pages)

**Comment by speplinski** [comment]
Done
