### ISSUE TITLE
Formy gramatyczne w pasku nawigacji w nagłówku

### ISSUE THREAD

**Issue by zwiastunsw** [irdpl/wcag#48]
W nawigacji pojawiają się niepoprawne formy gramatyczne:

- Poprzedni**e** Wytyczna zamiast Poprzedni**a** Wytyczna (lub lepiej Poprzednia wytyczna)
- Następn**e** Wytyczna zamiast Następn**a** Wytyczna  (lub lepiej Następna wytyczna)
![chrome_cmDaDiSasq](https://github.com/irdpl/wcag/assets/29527200/8f782d1e-0365-4efa-adae-cafa63167cf5)

**Comment by speplinski** [comment]
Poprawione
