### ISSUE TITLE
Forma gramatyczna w tytułach stron z objaśnieniami wytycznych 

### ISSUE THREAD

**Issue by zwiastunsw** [irdpl/wcag#49]
Mamy Objaśnienie Wytyczn**a**... zamiast Objaśnienie Wytyczn**ej**

![chrome_or4EVjbuDl](https://github.com/irdpl/wcag/assets/29527200/9c511c2e-9e2e-4c96-b5ed-516889d4ee4e)

**Comment by speplinski** [comment]
`Objaśnienie wytycznej 2.2` czy `Objaśnienie Wytycznej 2.2`?
W nawigacji poprawialiśmy słowo `Wytyczna` na `wytyczna`.
@zwiastunsw

**Comment by zwiastunsw** [comment]
Jest Ok - użyjmy tu wielkich liter
